EXTRA_CFLAGS += -Iarch/arm/mach-msm

obj-$(CONFIG_MACH_MSM7X25A_E0) += board-e0.o
obj-$(CONFIG_MACH_MSM7X25A_E0) += board-e0-input.o
obj-$(CONFIG_MACH_MSM7X25A_E0) += board-e0-misc.o
obj-$(CONFIG_MACH_MSM7X25A_E0) += board-e0-mmc.o
obj-$(CONFIG_MACH_MSM7X25A_E0) += board-e0-sound.o
obj-$(CONFIG_MACH_MSM7X25A_E0) += board-e0-panel.o
obj-$(CONFIG_MACH_MSM7X25A_E0) += board-e0-camera.o
obj-$(CONFIG_MACH_MSM7X25A_E0) += board-e0-pm.o
obj-$(CONFIG_MACH_MSM7X25A_E0) += board-e0-usb.o
obj-$(CONFIG_MACH_MSM7X25A_E0) += board-e0-connectivity.o
